# l = [1,2,3,4,5,3]
# l.extend("adb3")
# print(l)
# l.append("xyz")
# print(l)
# l.pop(6)
# print(l)
# l.remove("xyz")
# print(l)
# l.insert(5, 6)
# print(l)
# a = "Python Hello"
# L = list(a)
# print(L)
# n= l.index(3)
# print(n)